version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: fiber-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: beninf123
      POSTGRES_DB: go_fiber_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d go_fiber_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APP_URL=http://localhost:8080
      - DB_DSN=host=db user=postgres password=secret dbname=go_fiber_db port=5432 sslmode=disable TimeZone=Asia/Jakarta
      - JWT_PRIVATE_KEY_PATH=keys/jwt_private.pem
      - JWT_PUBLIC_KEY_PATH=keys/jwt_public.pem
      - JWT_EXPIRY_MINUTES=15
      - REFRESH_EXPIRY_DAYS=7
    volumes:
      - ./keys:/app/keys
      - ./storage:/app/storage
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
